source "https://rubygems.org"

ruby "2.4.1"

gem "fastlane", "2.145.0"

# Plugins
gem "fastlane-plugin-milan", git: "https://github.com/mderuiter/fastlane-plugin-milan"
gem "fastlane-plugin-sergio", git: "https://github.com/sergiogiucastro/fastlane-plugin-sergio"
gem "fastlane-plugin-petar", git: "https://github.com/PetarAnastasov/fastlane-plugin-petar"
gem "fastlane-plugin-carlo", git: "https://github.com/cmatulessy/fastlane-plugin-carlo"
gem "fastlane-plugin-niels", git: "https://github.com/Niels-Robben/fastlane-plugin-niels"
gem "fastlane-plugin-mario", git: "https://github.com/marionegroponzi/fastlane-plugin-mario"
gem "fastlane-plugin-rajesh", git: "https://github.com/whizbuff/fastlane-plugin-rajesh"
gem "fastlane-plugin-jinal", git: "https://github.com/jinal90/fastlane-plugin-jinal"
gem "fastlane-plugin-ziya", git: "https://github.com/ziyabal/fastlane-plugin-ziya"
gem "fastlane-plugin-joris", git: "https://github.com/jorisvg/fastlane-plugin-joris"
gem "fastlane-plugin-luciano", git: "https://github.com/lucianoluzzi/fastlane_plugin_luciano"
gem "fastlane-plugin-socratis", git: "https://github.com/SocratisM/fastlane-plugin-socratis"
gem "fastlane-plugin-frank", git: "https://github.com/frankdeboer1985/fastlane-plugin-frank"
gem "fastlane-plugin-debi", git: "https://github.com/debidutt87/fastlane-plugin-debi"
gem "fastlane-plugin-the_illest", git: "https://github.com/BakhtarSobat/fastlane-plugin-the_illest"
# gem "fastlane-plugin-dana", git: "https://github.com/Fininininies/fastlane-plugin-dana"
gem "fastlane-plugin-serdar", git: "https://github.com/yillars/fastlane-plugin-serdar"
gem "fastlane-plugin-uditha", git: "https://github.com/udithaR/fastlane-plugin-uditha"
gem "fastlane-plugin-fancysida", git: "https://github.com/51d4/fastlane-plugin-testPlugin"
gem "fastlane-plugin-jordan", git: "https://github.com/thejordan/dunyas-fastlane-workshop"
