default_platform(:ios)

platform :ios do
  lane :workshop do
    milan
    # sergio
    petar
    carlo
    niels
    mario
    rajesh
    jinal
    ziya
    joris
    luciano
    socratis
    frank
    debi
    the_illest
    # dana
    serdar
    uditha
    fancysida
    jordan
  end
end
